// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrucoSpecs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ManilhaDefinition")]
    public partial class ManilhaDefinitionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ManilhaDefinition.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ManilhaDefinition", "In order to determine the manilha of the turn\r\nAs a truco player\r\nI want to be gi" +
                    "ven the trump card and as a consequence discover the joker", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Define manilha suit")]
        [NUnit.Framework.CategoryAttribute("joker")]
        [NUnit.Framework.TestCaseAttribute("4", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("5", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("6", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("7", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("Q", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("J", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("K", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("A", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("2", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        [NUnit.Framework.TestCaseAttribute("3", "Clubs", "Hearts", "Spades", "Diamonds", null)]
        public virtual void DefineManilhaSuit(string trumpCard, string zap, string copas, string espadilha, string pica_Fumo, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "joker"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Define manilha suit", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("the turn is about to start", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("I show trump card <turn card>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then(string.Format("zap suit should be {0}", zap), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
 testRunner.And(string.Format("copas suit should be {0}", copas), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("espadilha suit should be {0}", espadilha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("pica-fumo suit should be {0}", pica_Fumo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
